# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_RAS)	+= ras.o
obj-$(CONFIG_DEBUG_FS)	+= debugfs.o
obj-$(CONFIG_RAS_CEC)	+= cec.o
obj-$(CONFIG_MEM_ACPI_RAS2)	+= acpi_ras2.o

obj-$(CONFIG_RAS_FMPM)	+= amd/fmpm.o
obj-y			+= amd/atl/
